version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: myPostgresContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: disco
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql